# Generated by Django 3.2.19 on 2023-11-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('education', models.CharField(max_length=125)),
                ('collegeAndCity', models.CharField(max_length=125)),
                ('yearOfPassing', models.IntegerField()),
                ('inPuneSince', models.IntegerField()),
                ('experience', models.CharField(max_length=125)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=125)),
                ('reference', models.CharField(max_length=125)),
                ('batchType', models.CharField(max_length=125)),
                ('comment', models.TextField()),
            ],
        ),
    ]
