# Generated by Django 3.2.19 on 2023-11-09 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='courseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
    ]
